blob_storage = "filesystem"
metadata_storage = "integrated"
listen_addr = ":8085"

[blob_storage_filesystem]
base_dir = "/tmp/modelboxblobs"

[metadata_storage_integrated]
path = "/tmp/modelbox.dat"

[metadata_storage_postgres]
host = "172.17.0.2"
port = 5432
user = "postgres"